apiVersion: v1
baseDomain: openinfra.lab
metadata:
  name: gpu-cluster
networking:
  machineNetwork:
  - cidr: 172.20.131.0/24
  networkType: OVNKubernetes
compute:
- name: worker
  replicas: 3
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIPs:
      - 172.20.131.31
    ingressVIPs:
      - 172.20.131.30
    provisioningNetworkCIDR: 172.20.132.0/24
    provisioningDHCPRange: 172.20.132.20,172.20.132.39
    clusterProvisioningIP: 172.20.132.13
    bootstrapProvisioningIP: 172.20.132.12
    bootstrapExternalStaticIP: 172.20.131.12
    bootstrapExternalStaticDNS: 172.20.129.10
    bootstrapExternalStaticGateway: 172.20.131.1
    hosts:
      - name: ocp-gpu-control1
        role: master
        bmc:
          address: ipmi://172.20.254.40
          username: secret
          password: secret
        bootMACAddress: 00:0e:1e:aa:e3:d0
        rootDeviceHints:
         deviceName: "/dev/sda"
        networkConfig:
          interfaces:
          - name: ens1f1 
            type: ethernet
            state: up
            ipv4:
              address:
              - ip: 172.20.131.20
                prefix-length: 24
              enabled: true
          dns-resolver:
            config:
              server:
              - 172.20.129.10
          routes:
            config:
            - destination: 0.0.0.0/0
              next-hop-address: 172.20.131.1
              next-hop-interface: ens1f1
      - name: ocp-gpu-control2
        role: master
        bmc:
          address: ipmi://172.20.254.41
          username: secret
          password: secret
        bootMACAddress: 00:0e:1e:aa:de:20
        rootDeviceHints:
         deviceName: "/dev/sda"
        networkConfig:
          interfaces:
          - name: ens1f1     
            type: ethernet
            state: up
            ipv4:
              address:
              - ip: 172.20.131.21
                prefix-length: 24
              enabled: true
          dns-resolver:
            config:
              server:
              - 172.20.129.10
          routes:
            config:
            - destination: 0.0.0.0/0
              next-hop-address: 172.20.131.1
              next-hop-interface: ens1f1
      - name: ocp-gpu-control3
        role: master
        bmc:
          address: ipmi://172.20.254.42
          username: secret
          password: secret
        bootMACAddress: 00:0e:1e:aa:c6:a0
        rootDeviceHints:
         deviceName: "/dev/sda"
        networkConfig:
          interfaces:
          - name: ens1f1     
            type: ethernet
            state: up
            ipv4:
              address:
              - ip: 172.20.131.22
                prefix-length: 24
              enabled: true
          dns-resolver:
            config:
              server:
              - 172.20.129.10
          routes:
            config:
            - destination: 0.0.0.0/0
              next-hop-address: 172.20.131.1
              next-hop-interface: ens1f1
      - name: ocp-gpu-worker1
        role: worker
        bmc:
          address: ipmi://172.20.254.60
          username: secret
          password: secret
        bootMACAddress: 90:e2:ba:bf:36:24
        rootDeviceHints:
         wwnWithExtension: "0x600605b00b8bd3102d03689a076f7096"
        networkConfig:
          interfaces:
          - name: ens4f1
            type: ethernet
            state: up
            ipv4:
              address:
              - ip: 172.20.131.23
                prefix-length: 24
              enabled: true
          dns-resolver:
            config:
              server:
              - 172.20.129.10
          routes:
            config:
            - destination: 0.0.0.0/0
              next-hop-address: 172.20.131.1
              next-hop-interface: ens4f1
      - name: ocp-gpu-worker2
        role: worker
        bmc:
          address: ipmi://172.20.254.61
          username: secret
          password: secret
        bootMACAddress: 90:e2:ba:c1:77:64
        rootDeviceHints:
         wwnWithExtension: "0x600605b00b8be4a02d03631321adfb24"
        networkConfig:
          interfaces:
          - name: ens4f1
            type: ethernet
            state: up
            ipv4:
              address:
              - ip: 172.20.131.24
                prefix-length: 24
              enabled: true
          dns-resolver:
            config:
              server:
              - 172.20.129.10
          routes:
            config: 
            - destination: 0.0.0.0/0
              next-hop-address: 172.20.131.1
              next-hop-interface: ens4f1
      - name: ocp-gpu-worker3
        role: worker
        bmc:
          address: ipmi://172.20.254.62
          username: secret
          password: secret
        bootMACAddress: 90:e2:ba:c3:cd:00
        rootDeviceHints:
         wwnWithExtension: "0x600605b00b8bdeb02d036673547556b0"
        networkConfig:
          interfaces:
          - name: ens4f1
            type: ethernet
            state: up
            ipv4:
              address:
              - ip: 172.20.131.25
                prefix-length: 24
              enabled: true
          dns-resolver:
            config:
              server:
              - 172.20.129.10
          routes:
            config: 
            - destination: 0.0.0.0/0
              next-hop-address: 172.20.131.1
              next-hop-interface: ens4f1
pullSecret: '{"auths":{"cloud.openshift.com"...'
sshKey: 'ssh-rsa....'
